name: Apply Terraform on Merge to master

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CRENTIALS: ${{ secrets.GOOGLE_CRENTIALS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ">= 1.2.0" # Specify your Terraform version here

      - name: Terraform init
        working-directory: terraform/config
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "secret_variable=${{ env.GOOGLE_CRENTIALS }}"

      # - name: Terraform plan
      #   working-directory: terraform/config
      #   run: terraform plan -var "secret_variable=${{ secrets.GOOGLE_CRENTIALS }}"

      - name: Terraform apply
        working-directory: terraform/config
        if: github.ref == 'refs/heads/master' # Run apply only for master branch
        run: terraform apply -auto-approve -var "secret_variable=${{ secrets.GOOGLE_CRENTIALS }}"
        # You might want to add additional options here such as auto-approving the apply with `-auto-approve` flag
